# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'SunnyTMDB' do
  pod 'Alamofire', '~> 5.4'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
  end
 end
end
